import { Worker, Booking, Review, Notification, WalletTransaction, Category } from './types';

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Plumber', name_hindi: 'प्लंबर', icon: 'droplets', color: '#2563EB', workers_count: 24, is_active: true, sort_order: 1 },
  { id: '2', name: 'Electrician', name_hindi: 'इलेक्ट्रीशियन', icon: 'zap', color: '#F59E0B', workers_count: 32, is_active: true, sort_order: 2 },
  { id: '3', name: 'Painter', name_hindi: 'पेंटर', icon: 'paintbrush', color: '#8B5CF6', workers_count: 18, is_active: true, sort_order: 3 },
  { id: '4', name: 'Carpenter', name_hindi: 'बढ़ई', icon: 'hammer', color: '#D97706', workers_count: 15, is_active: true, sort_order: 4 },
  { id: '5', name: 'AC Repair', name_hindi: 'एसी रिपेयर', icon: 'wind', color: '#06B6D4', workers_count: 12, is_active: true, sort_order: 5 },
  { id: '6', name: 'Bike Mechanic', name_hindi: 'बाइक मैकेनिक', icon: 'bike', color: '#10B981', workers_count: 28, is_active: true, sort_order: 6 },
  { id: '7', name: 'Car Mechanic', name_hindi: 'कार मैकेनिक', icon: 'car', color: '#EF4444', workers_count: 20, is_active: true, sort_order: 7 },
  { id: '8', name: 'Cleaner', name_hindi: 'सफाई वाले', icon: 'sparkles', color: '#6366F1', workers_count: 35, is_active: true, sort_order: 8 },
  { id: '9', name: 'Driver', name_hindi: 'ड्राइवर', icon: 'navigation', color: '#14B8A6', workers_count: 40, is_active: true, sort_order: 9 },
  { id: '10', name: 'Tutor', name_hindi: 'ट्यूटर', icon: 'book-open', color: '#F97316', workers_count: 22, is_active: true, sort_order: 10 },
  { id: '11', name: 'Mason', name_hindi: 'राजमिस्त्री', icon: 'layers', color: '#84CC16', workers_count: 16, is_active: true, sort_order: 11 },
  { id: '12', name: 'Welder', name_hindi: 'वेल्डर', icon: 'flame', color: '#DC2626', workers_count: 11, is_active: true, sort_order: 12 },
];

export const MOCK_WORKERS: Worker[] = [
  {
    id: 'w1',
    user_id: 'u1',
    category_id: '2',
    category_name: 'Electrician',
    experience_years: 8,
    hourly_rate: 250,
    daily_rate: 1500,
    description: 'Experienced electrician with 8+ years. Specializes in home wiring, AC installation, and panel upgrades.',
    service_areas: ['Lajpat Nagar', 'South Delhi', 'Nehru Place'],
    skills: ['Home Wiring', 'AC Installation', 'Panel Upgrade', 'CCTV'],
    portfolio_images: [
      'https://images.pexels.com/photos/257736/pexels-photo-257736.jpeg?w=400',
      'https://images.pexels.com/photos/162553/keys-workshop-mechanic-tools-162553.jpeg?w=400',
    ],
    is_available: true,
    is_verified: true,
    is_approved: true,
    is_featured: true,
    rating: 4.8,
    total_reviews: 124,
    total_jobs: 312,
    total_earnings: 185000,
    wallet_balance: 12500,
    work_timing_start: '08:00',
    work_timing_end: '20:00',
    city: 'Delhi',
    profiles: {
      id: 'u1',
      full_name: 'Ramesh Kumar',
      phone: '+91 98765 43210',
      avatar_url: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?w=200',
      role: 'worker',
      city: 'Delhi',
      address: 'Lajpat Nagar, Delhi',
      is_active: true,
      is_banned: false,
      created_at: '2023-01-15',
    }
  },
  {
    id: 'w2',
    user_id: 'u2',
    category_id: '1',
    category_name: 'Plumber',
    experience_years: 5,
    hourly_rate: 200,
    daily_rate: 1200,
    description: 'Professional plumber specializing in pipe fitting, leakage repair, and bathroom installation.',
    service_areas: ['Dwarka', 'Janakpuri', 'Uttam Nagar'],
    skills: ['Pipe Fitting', 'Leakage Repair', 'Bathroom Installation', 'Water Heater'],
    portfolio_images: [
      'https://images.pexels.com/photos/1078882/pexels-photo-1078882.jpeg?w=400',
    ],
    is_available: true,
    is_verified: true,
    is_approved: true,
    is_featured: false,
    rating: 4.5,
    total_reviews: 87,
    total_jobs: 198,
    total_earnings: 95000,
    wallet_balance: 8200,
    work_timing_start: '07:00',
    work_timing_end: '19:00',
    city: 'Delhi',
    profiles: {
      id: 'u2',
      full_name: 'Suresh Yadav',
      phone: '+91 87654 32109',
      avatar_url: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?w=200',
      role: 'worker',
      city: 'Delhi',
      address: 'Dwarka, Delhi',
      is_active: true,
      is_banned: false,
      created_at: '2023-03-20',
    }
  },
  {
    id: 'w3',
    user_id: 'u3',
    category_id: '5',
    category_name: 'AC Repair',
    experience_years: 10,
    hourly_rate: 350,
    daily_rate: 2000,
    description: 'AC specialist with 10 years experience. Handle all brands - Samsung, LG, Daikin, Hitachi, Voltas.',
    service_areas: ['Connaught Place', 'Karol Bagh', 'Paharganj'],
    skills: ['AC Service', 'Gas Filling', 'Compressor Repair', 'Installation'],
    portfolio_images: [],
    is_available: false,
    is_verified: true,
    is_approved: true,
    is_featured: true,
    rating: 4.9,
    total_reviews: 231,
    total_jobs: 540,
    total_earnings: 420000,
    wallet_balance: 25000,
    work_timing_start: '09:00',
    work_timing_end: '21:00',
    city: 'Delhi',
    profiles: {
      id: 'u3',
      full_name: 'Vijay Singh',
      phone: '+91 76543 21098',
      avatar_url: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?w=200',
      role: 'worker',
      city: 'Delhi',
      address: 'Karol Bagh, Delhi',
      is_active: true,
      is_banned: false,
      created_at: '2022-09-10',
    }
  },
  {
    id: 'w4',
    user_id: 'u4',
    category_id: '3',
    category_name: 'Painter',
    experience_years: 6,
    hourly_rate: 180,
    daily_rate: 1000,
    description: 'Interior and exterior painting expert. Use Asian Paints, Berger and all premium brands.',
    service_areas: ['Rohini', 'Pitampura', 'Shalimar Bagh'],
    skills: ['Interior Painting', 'Exterior Painting', 'Texture Work', 'Waterproofing'],
    portfolio_images: [
      'https://images.pexels.com/photos/1669754/pexels-photo-1669754.jpeg?w=400',
      'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?w=400',
    ],
    is_available: true,
    is_verified: true,
    is_approved: true,
    is_featured: false,
    rating: 4.6,
    total_reviews: 98,
    total_jobs: 156,
    total_earnings: 78000,
    wallet_balance: 5400,
    work_timing_start: '08:00',
    work_timing_end: '18:00',
    city: 'Delhi',
    profiles: {
      id: 'u4',
      full_name: 'Manoj Sharma',
      phone: '+91 65432 10987',
      avatar_url: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?w=200',
      role: 'worker',
      city: 'Delhi',
      address: 'Rohini, Delhi',
      is_active: true,
      is_banned: false,
      created_at: '2023-05-12',
    }
  },
  {
    id: 'w5',
    user_id: 'u5',
    category_id: '8',
    category_name: 'Cleaner',
    experience_years: 3,
    hourly_rate: 150,
    daily_rate: 800,
    description: 'Home and office cleaning services. Deep cleaning, sofa cleaning, and carpet cleaning available.',
    service_areas: ['Noida', 'Greater Noida', 'Ghaziabad'],
    skills: ['Home Cleaning', 'Deep Cleaning', 'Sofa Cleaning', 'Office Cleaning'],
    portfolio_images: [],
    is_available: true,
    is_verified: false,
    is_approved: true,
    is_featured: false,
    rating: 4.3,
    total_reviews: 45,
    total_jobs: 89,
    total_earnings: 35000,
    wallet_balance: 2800,
    work_timing_start: '07:00',
    work_timing_end: '17:00',
    city: 'Noida',
    profiles: {
      id: 'u5',
      full_name: 'Priya Devi',
      phone: '+91 54321 09876',
      avatar_url: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?w=200',
      role: 'worker',
      city: 'Noida',
      address: 'Sector 62, Noida',
      is_active: true,
      is_banned: false,
      created_at: '2024-01-08',
    }
  },
];

export const MOCK_REVIEWS: Review[] = [
  { id: 'r1', booking_id: 'b1', customer_id: 'cu1', worker_id: 'w1', rating: 5, comment: 'Bahut acha kaam kiya! Bahut professional. Sab kuch ek dum sahi kiya.', created_at: '2024-01-15', profiles: { id: 'cu1', full_name: 'Amit Verma', phone: '', avatar_url: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?w=200', role: 'customer', city: 'Delhi', address: '', is_active: true, is_banned: false, created_at: '' } },
  { id: 'r2', booking_id: 'b2', customer_id: 'cu2', worker_id: 'w1', rating: 5, comment: 'Very punctual and professional. Fixed the issue quickly. Highly recommended!', created_at: '2024-01-20', profiles: { id: 'cu2', full_name: 'Neha Singh', phone: '', avatar_url: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?w=200', role: 'customer', city: 'Delhi', address: '', is_active: true, is_banned: false, created_at: '' } },
  { id: 'r3', booking_id: 'b3', customer_id: 'cu3', worker_id: 'w1', rating: 4, comment: 'Good work, came on time. Will hire again for next project.', created_at: '2024-02-01', profiles: { id: 'cu3', full_name: 'Rajesh Gupta', phone: '', avatar_url: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?w=200', role: 'customer', city: 'Delhi', address: '', is_active: true, is_banned: false, created_at: '' } },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    customer_id: 'cu1',
    worker_id: 'w1',
    status: 'completed',
    problem_description: 'Electrical wiring issue in kitchen. Some switches not working properly.',
    problem_images: [],
    scheduled_date: '2024-01-15',
    scheduled_time: '10:00 AM',
    address: 'A-234, Lajpat Nagar, New Delhi',
    city: 'Delhi',
    estimated_cost: 800,
    final_cost: 750,
    is_emergency: false,
    created_at: '2024-01-14',
    workers: MOCK_WORKERS[0],
  },
  {
    id: 'b2',
    customer_id: 'cu1',
    worker_id: 'w2',
    status: 'accepted',
    problem_description: 'Bathroom pipe leakage. Water dripping from under the sink.',
    problem_images: [],
    scheduled_date: '2024-02-20',
    scheduled_time: '2:00 PM',
    address: 'A-234, Lajpat Nagar, New Delhi',
    city: 'Delhi',
    estimated_cost: 500,
    final_cost: 0,
    is_emergency: false,
    created_at: '2024-02-18',
    workers: MOCK_WORKERS[1],
  },
  {
    id: 'b3',
    customer_id: 'cu1',
    worker_id: 'w3',
    status: 'pending',
    problem_description: 'AC not cooling properly. Need servicing and gas refill.',
    problem_images: [],
    scheduled_date: '2024-03-05',
    scheduled_time: '11:00 AM',
    address: 'A-234, Lajpat Nagar, New Delhi',
    city: 'Delhi',
    estimated_cost: 1200,
    final_cost: 0,
    is_emergency: false,
    created_at: '2024-03-03',
    workers: MOCK_WORKERS[2],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'n1', user_id: 'cu1', title: 'Booking Confirmed', message: 'Ramesh Kumar ne aapki booking accept kar li hai. Kal 10 baje aayenge.', type: 'booking', is_read: false, created_at: '2024-02-19T10:30:00' },
  { id: 'n2', user_id: 'cu1', title: 'Job Completed', message: 'Suresh Yadav ne aapka kaam complete kar diya. Rating dena na bhoolein!', type: 'booking', is_read: false, created_at: '2024-01-15T16:00:00' },
  { id: 'n3', user_id: 'cu1', title: 'Special Offer!', message: 'Aaj AC Repair pe 20% discount. Limited time offer. Abhi book karein!', type: 'general', is_read: true, created_at: '2024-01-10T09:00:00' },
  { id: 'n4', user_id: 'cu1', title: 'New Worker Available', message: 'Aapke area mein ek naye verified electrician ne join kiya hai.', type: 'general', is_read: true, created_at: '2024-01-08T11:00:00' },
];

export const MOCK_TRANSACTIONS: WalletTransaction[] = [
  { id: 't1', worker_id: 'w1', booking_id: 'b1', type: 'credit', amount: 675, status: 'completed', description: 'Booking earnings (after 10% commission)', created_at: '2024-01-15T17:00:00' },
  { id: 't2', worker_id: 'w1', booking_id: 'b4', type: 'credit', amount: 900, status: 'completed', description: 'Booking earnings (after 10% commission)', created_at: '2024-01-12T15:00:00' },
  { id: 't3', worker_id: 'w1', type: 'withdrawal', amount: -2000, status: 'completed', description: 'Withdrawal to bank account', created_at: '2024-01-10T12:00:00' },
  { id: 't4', worker_id: 'w1', type: 'bonus', amount: 500, status: 'completed', description: 'Monthly performance bonus', created_at: '2024-01-01T09:00:00' },
];
